/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    '& Quantum Reset': '& 量子重置',
    'Quantity': '数量',
    'Quantum': '量子',
    'Qubit': '量子位',
    'Research': '研究',
    'Restart': '重新开始',
    'name': '名称',
    'New Age': '新世纪',
    'None': '无',
    'Output': '输出',
    'Money': '货币',
    'Challenge': '挑战',
    'Cost': '成本',
    'Export': '导出',
    'Extra Digit': '额外数位',
    'Hard Reset': '硬复位',
    'Hotkeys': '快捷键',
    'hehe': '呵呵',
    'Import': '导入',
    'Incrementer': '增量器',
    'Infinity Boost': '无限提升',
    'Lab Town': '实验室镇',
    'Make': '制作',
    'More Challenges': '更多挑战',
    'Multi Process': '多进程',
    'My Discord': '我的Discord',
    'Reboot': '重启',
    'Reboot Cool Down': '重新启动冷却',
    'Programs': '程序',
    'load': '加载',
    'Make speed': '制作速度',
    'Larger Memory': '更大的内存',
    'Infinity Research': '无限研究',
    'Lab': '实验室',
    'Durability': '耐用性',
    'Run': '运行',
    'Sacrifice': '牺牲',
    'Save': '保存',
    'Shop': '商店',
    'Singularit': '奇点',
    'Singularity': '奇点',
    'Speed': '速度',
    'Stat': '统计',
    'Ultimate Science': '终极科学',
    'Upgrades': '升级',
    'Upgrade!': '升级!',
    'Base': '基数',
    'Boost!': '提升!',
    'Booster': '加速器',
    'Bugged Reality': '错误的现实',
    'Broken Machine': '破碎机',
    'Bulk QL Challenge': '散装QL挑战',
    'CPU upgrade level +': 'CPU升级等级 +',
    'decrease speed /': '降低速度 /',
    'Digit': '数位',
    'Boost': '提升',
    'Effects': '效果',
    'Exit challenge': '退出挑战',
    'Game speed': '游戏速度',
    'Tech lab?': '技术实验室？',
    'Second Singularity': '第二奇点',
    'Skilled': '熟练',
    'Rich': '富有',
    'Richer': '更富有',
    'Respec': '规格',
    'Bonus CPU Level': '额外的CPU等级',
    'Multiply mine power by Digits': '数位乘以矿山的力量',
    'RP Gain': '研究点收益',
    'RP gain': '研究点收益',
    'Sacrifice II': '牺牲 II',
    'Savefiles': '保存文件',
    'Theme: Default': '主题: 默认',
    'Theme: None': '主题: 无',
    'Tricky': '棘手',
    'Undo': '撤销',
    'x faster': 'x 更快',
    'Grid': '网格',
    'Grid Lab': '网格实验室',
    'Infinity': '无限',
    'Info': '信息',
    'Merger': '合并',
    'Mastered': '精通',
    'Max digit +': '最大数位 +',
    'Lv.': '等级',
    'Max Durability': '最大耐久度',
    'Max program run at one time +': '一次最多可运行程序+',
    'Memory exceed': '内存超过',
    'Mult': '倍数',
    'R.Speed': 'R.速度',
    'la la la': '啦啦啦',
    'Inf..': '无限..',
    'R: reboot': 'R: 重启',
    'Q: build lab': 'Q: 建造实验室',
    '8: Toggle all programs': '8：切换所有程序',
    '1 ~ 7: Toggle program 1~': '1〜7：切换程序1〜',
    'Go singularity one more time': '再来一次奇点',
    'Go Singularity in 1e+110/500 milliseconds': '在1e+110/500毫秒内到达奇点',
    'Go singularity': '到达奇点',
    'Complete a challenge': '完成一个挑战',
    'Complete Boost Challenge': '完成提升挑战',
    'Complete Boost Challenge once': '完成提升挑战一次',
    'Complete Qubit Challenge once': '完成量子位挑战一次',
    'Can bulk complete Challenge': '可以批量完成挑战',
    'Buy all Quantum Upgrades': '购买所有量子升级',
    'All Challenge requirement -': '所有挑战要求-',
    'Increase digit won\'t reset anything': '增加数位不会重置任何东西',
    'your Base and Programs on reboot': '你的基数和程序在重启时',
    'More Quantum Upgrades': '更多量子升级',
    'Multiply Mine power by': '挖矿功率乘以',
    'Multiply mine power by': '挖矿功率乘以',
    'Multiply RP gain based on itself': '根据自身乘以研究点增益',
    'nvaild savefile!': '无效的存档文件！',
    'speed': '速度',
    'Speed': '速度',
    'Reward': '奖励',
    'save': '保存',
    'savefile!': '存档文件！',
    'Shift Qubit production by +': '将量子位产生量改为 +',
    'Start challenge with half of goal QL (max.': '开始挑战的一半目标QL(最大。',
    'Start Quantum run with 100 RP': '启动量子运行100研究点',
    'Theme: Aqua': '主题：水色',
    'Theme: Compact': '主题：紧凑',
    'Theme: Magenta (by RedMountain': '主题：洋红色（作者：RedMountain',
    'to clipboard': '到剪贴板',
    'way too long': '太久',
    '^0.9 Quantum requirements': '^ 0.9量子需求',
    'CPU speed': 'CPU速度',
    'Go Infinity in 10 seconds': '在10秒内达到无限',
    "Qubit production speed": "量子位的生产速度",
    "Reach 111111(": "达到 111111(",
    'SP gain': 'SP 收益',
    'upgrade CPU': '升级CPU',
    'Achievement: A Dollar': '成就：一美元',
    'time / x IP': '时间 / x 无限点',
    'Infinity QL': '无限 QL',
    'Multiply mine power by Research Point': '通过研究点乘以矿山的能量',
    'You lose': '你会损失',
    'You lose Money, Upgrades': '你会损失金钱和升级',
    'You lose Money, Upgrades, Digit, Number': '你会损失金钱和升级，数位，数字',
    'You lose Money, Upgrades, Digit, Number, Base': '你会损失金钱和升级，数位，数字, 基于',
    'Boost List': '提升列表',
    'You have': '你有',
    'You need 80 Quantum Labs to go Singularity': '需要80个量子实验室才能实现奇点',
    'Have a 1 $': '有 1 $',
    'Reduce Quantum Lab requirement isn\'t allowed': '不允许减少量子实验室的要求',
    'Lock Durability and Max durability research': '锁定耐久性和最大耐久性研究',
    'CPU upgrade effect ^': 'CPU升级效果^',
    'Complete 1 more challenge to unlock 25th Grid space': '完成更多1个挑战解锁第25格空间',
    'All quantum upgrade cost': '所有量子升级成本',
    'And boosts grid machine Power by': '并提升网格机器的功率',
    'is capped at 50 (can extend with only grid': '上限为50（只能用网格扩展',
    'Digit is capped at 20 (can extend with only grid': '位数上限为20（只能用网格扩展',
    'Divide research upgrade effect by': '将研究升级效果除以',
    'Each Qubit makes your CPU 2x faster (': '每个量子位可使您的CPU快2倍（',
    'Each SP increases Multi Process by 4 (tot 200025, softcap at': '每个SP将多线程增加4（总计 200025，软上限为',
    'Effects of all previous Challenges': '先前所有挑战的影响',
    'Each Qubit multiply Mine Power by': '每个量子位将矿山能量乘以',
    'Name: Incrementer': '名称：增量器',
    'Nothing here': '这里什么都没有',
    'Increase base won\'t reset anything': '增加基数不会重置任何东西',
    'your Money and Upgrade on reboot': '你的金钱和升级在重启时',
    'research buy third row': '研究购买第三行',
    'Boost RP gain based on Qubit and RP (': '根据量子位和研究点提高研究点增益（',
    'Complete 1 more challenge to unlock 5th Grid space': '完成更多一项挑战，解锁第五格空间',
    'Increase base won\'t reset memory': '增加基数不会重置内存',
    'LM: rotate': 'LM: 旋转',
    'RM: remove': 'RM: 移除',
    'Multiply mine power by Overclock Power': '通过超频能量倍增矿用能量',
    'Name: Money': '名称：金钱',
    'Name: Output': '名称: 输出',
    'Perform Overclock': '执行超频',
    'Perform Quantum': '执行量子',
    'Perform Reboot': '执行重启',
    'Reach 1Q(': '达到 1Q(',
    'Value': '值',
    '> Power': '> 能量',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'WARNING! You haven\'t activated Data_Holder.exe!': '警告！ 您尚未激活Data_Holder.exe！',
    'Reach 1B(': '达到 1B(',
    'Go Singularity in 83364650/500 milliseconds': '在83364650/500毫秒内达到奇点',
    'Overclocker.exe': 'Overclocker.exe（超频）',
    'Miner_3.0.exe': 'Miner_3.0.exe（挖矿3.0，赚更多更多钱）',
    'Miner_2.0.exe': 'Miner_2.0.exe（挖矿2.0，赚更多更多钱）',
    'Miner_4.0.exe': 'Miner_4.0.exe（挖矿4.0，赚更多更多钱）',
    'Mine_2.0.exe': 'Mine_2.0.exe（挖矿2.0，赚更多钱）',
    'Mine.exe': 'Mine.exe（挖矿，赚钱）',
    'Memory.exe': 'Memory.exe（内存）',
    'Memory_2.0.exe': 'Memory_2.0.exe（内存2.0）',
    'Memory_3.0.exe': 'Memory_3.0.exe（内存3.0）',
    'Memory_4.0.exe': 'Memory_4.0.exe（内存4.0）',
    'Increment.exe': 'Increment.exe（增量）',
    'Data_Holder.exe': 'Data_Holder.exe（数据容器）',
    'Data_Holder_2.0.exe': 'Data_Holder_2.0.exe（数据容器2.0）',
    'Data_Holder_3.0.exe': 'Data_Holder_3.0.exe（数据容器3.0）',
    'Base_Increaser.exe': 'Base_Increaser.exe（基础增量器）',
    'Base_Increaser_2.0.exe': 'Base_Increaser_2.0.exe（基础增量器2.0）',
    'Base_Increaser_3.0.exe': 'Base_Increaser_3.0.exe（基础增量器3.0）',
    'Base_Increaser_4.0.exe': 'Base_Increaser_4.0.exe（基础增量器4.0）',
    'Base_Increaser_5.0.exe': 'Base_Increaser_5.0.exe（基础增量器5.0）',
    'Auto_Upgrader.exe': 'Auto_Upgrader.exe（自动升级）',
    "Data_Holder.exe will keep through Quantum": "Data_Holder.exe将保持整个量子",
    'Boost Research speed based on Time spent on this quantum and RP (': '根据花费在这个量子和研究点上的时间来提高研究速度(',
    "And sqrt Quantum Lab Money req": "和开方量子实验室金钱需求",
    "And sqrt Quantum Lab RP req": "和开方量子实验室研究点需求",
    "Boost Qubit production speed based on Number (": "提高基于数字的量子位生产速度(",
    '"Maximum Base"': '“最大基数”',
    '"Digits based on Number/s"': '“基于数字的数位/每秒”',
    '\'Bonus CPU Level\' research\'s effect': '“奖金CPU水平”研究效果',
    'Program buy': '程序购买',
    'You can click Automate upgrades again to toggle them!': '您可以再次单击“自动升级”以切换它们！',
    'You can bulk buy Research upgrades and Shop upgrades': '您可以批量购买研究升级和商店升级',
    'You can bulk buy Quantum Labs': '您可以批量购买量子实验室',
    'will land you to': '会带你到',
    'The Quantum requirements based on Base (^': '量子需求基于基数 (^',
    'Start run with level 2 Multi Process': '从2级多进程开始运行',
    'RP boosts CPU (': '研究点提升CPU (',
    'levels boosts RP gain (': '等级提升研究点收益(',
    'research buy first row': '研究购买第一行',
    'research buy second row': '研究购买第二行',
    'Remove money requirement from research': '将资金要求从研究中移除',
    'Quantum Lab': '量子实验室',
    'Memory.exe boost works if maximum digit is greater than': 'Memory.exe 提升工作，如果最高位数大于',
    'bought Programs (~Lv': '已购买的程序（〜等级',
    'bought Programs (All': '已购买的程序（全部',
    'all research for Level': '所有的研究等级',
    'all research and CPU Upgrade': '所有研究和CPU升级',
    'Instant finish Qubit make if pending time is less than 7 mins': '即时完成量子位制作，如果等待时间小于7分钟',
    'Increase digit cap based on base (+': '根据基数增加数位上限（+',
    'If max base is bigger than 2000, this bonus will based on max Digit': '如果最大基数大于2000，则此奖励将基于最大位数',
    'Generate RP per second based on Reboot cooldown (': '根据重新启动的冷却时间每秒生成研究点（',
    'Extend base cap based on Digits': '基于数位扩展基础上限',
    'your Digit and Number on reboot': '数位和数字在重启时',
    'You lose Money, Upgrades, Digit, Number on Reboot': '您在重启时会损失金钱，升级，数位和数字',
    'import string to game': '导入存档字符到游戏',
    'Boost Qubit gain speed based on Challenge Completions (^': '提高量子位加速基于挑战完成(^',
    'A, S, D, F, G, H, J: Open tabs': 'A, S, D, F, G, H, J: 打开标签',
    '2 more?': '再来2个?',
    '2 Merger Grid Machine': '2合并网格机',
    '2 Grid Space': '2网格空间',
    'You need to reach 11110100001000111111111111(2) to get next RP': '需要到达11110100001000111111111111(2)才能得到下一个研究点',
    'You lose Money, Upgrades, Digit, Number, Base on Reboot': '您会因重启而损失金钱，升级，数位，数字',
    'export game to clipboard': '导出存档到剪贴板',
    'file!': '文件!',
    'game to clipboard': '存档到剪贴板',
    'Generate 10% of SP gain per second': '每秒产生10%的SP增益',
    'Go Infinity in 5 hours': '在5个小时内达到无限',
    'your base(cap: 36), programs on reboot': '你的基数（上限：36），程序在重启时',
    'Need 80 Quantum Labs to go Singularity': '需要80个量子实验室才能实现奇点',
    'Power of Science': '科学的力量',
    'one machine of its type, as well as one extra Incrementer machine, SP and Qubit': '一台同类型的机器，以及一台额外的增量机，SP和量子位',
    'Offline Progress': '离线进度',
    'Notation: Logarithm': '符号:对数',
    'Notation: Default': '符号:默认',
    'Make it better, but durability will decrease faster': '让它变得更好，但是耐用性会下降得更快',
    'If you Reboot now, you\'ll get 0 Research Points': '如果你现在重启，你将得到0个研究点',
    'Give me more QUBIT!': '给我更多的量子位！',
    'Each Qubit makes your CPU 2x faster': '每一个量子位都使你的CPU速度提高两倍',
    'Digit +': '数位 +',
    'Ctrl: See advanced information': 'Ctrl:查看高级信息',
    'Complete 4 more challenges to unlock 5th Grid space': '完成更多4个挑战，解锁第五个格子空间',
    'Clicking the above upgrade will use 10% of your IP': '点击以上升级将使用10%的IP',
    'Challenge completion reward is': '挑战完成奖励是',
    'Buy upgrade for': '购买升级',
    'Shift + H: Toggle Hyper mode! - More fancy effects, more lag!': 'Shift + H:切换超模式!-更多的特效，更多的延迟!',
    'Shift + P: Pause the game': 'Shift + P:暂停游戏',
    'Singularity at light speed': '光速奇点',
    'You have 0/0 Qubit (next Qubit at Infinity sec': '你有0/0量子位(下一个量子位在无穷秒',
    'You have 0 Quantum Lab which makes Qubit Prodution 0x faster': '你有0量子实验室，使量子位的生产速度快0x',
    'You lose Number, Memery, Base, Monsy, Upgrades on Reboot': '您在重新启动时丢失了数字，内存，基数，金钱，升级',
    'You have 0 Infinity Points': '你有 0 无限点',
    'Reward of challenges are one of it\'s Machine, a Incrementer, a SP and a Extra Qubit': '挑战的奖励是它的一个机器，一个增量器，一个SP和一个额外的量子位元',
    'Shift + 1 ~ 8: Buy research 1 ~': 'Shift + 1〜8：购买研究1〜',
    'Upgrade durability to use overclock longer': '升级耐用性以延长超频时间',
    'Buy CPU upgrade automatically': '购买CPU自动升级',
    'You\'ve played this game for': '你玩了这个游戏',
    'You need to reach 63,999,999(10) to Reboot': '您需要达到63,999,999（10）才能重启',
    'Increase your base to store more number': '增加你的基数存储更多的数字',
    'Let\'s count to ten': '数到十',
    'Overclocker effect x2, but Durability decrease speed +': '超频效果x2，但耐用性降低速度 +',
    'Multiply mine power by digits': '通过数位乘以矿用电力',
    'A Dollar': '一美元',

    //原样
    'test desc': '测试描述',
    'RP': '研究点',
    'SP': 'SP',
    'IP': '无限点',
    'GG': 'GG',
    'Hz': 'Hz',
    'CPU': 'CPU',
    'TPS': 'TPS',
    '???': '???',
    '...': '...',
    '▲': '▲',
    '▼': '▼',
    '> _': '> _',
    '"Memory.exe"': '"Memory.exe"',
    '"Base_Increaser.exe"': '"Base_Increaser.exe"',
    'Module': '模块',
    'Option': '选项',
    'Achievement': '成就',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "Quantum ": "量子",
    'Number': '数字',
    "Overclock ": "超频",
    'Durability ': '耐用性',
    "Speed Challenge ": "速度挑战",
    "Start durability": "开始耐久性",
    "Challene Fail:": "挑战失败:",
    "Booster Challenge": "助推器挑战",
    "Next Lab:": "下个实验室:",
    "Reboot Cooldown": "重启冷却",
    "RP Challenge (": "研究点挑战 (",
    "A to ": "A 到 ",
    "Digit Challenge (": "数位挑战 (",
    "Money Challenge (": "金钱挑战 (",
    "Goal: ": "目标: ",
    "Process ": "进程 ",
    "Digit: ": "数位: ",
    "Base: ": "基数: ",
    "Qubit Challenge (": "量子位挑战 (",
    "R.Speed Challenge (": "重启速度调整 (",
    "Reboot cooldown ": "重启冷却时间 ",
    "Reach base ": "达到基数 ",
    "Reach Bonus CPU Level ": "达到奖励CPU等级 ",
    "Reach Extra Digit Level ": "达到额外数位等级 ",
    "Reach Infinity$ (cap of ": "达到无限$ (上限是 ",
    "Reach Multi Process Level ": "达到多进程等级 ",
    "Shop cost": "商店成本",
    "Perform Overclock with Power ": "用能量进行超频 ",
    "start ": "启动 ",
    "Record: ": "记录:",
    "Tier: ": "层: ",
    "Cost: ": "成本: ",
    "Automate ": "自动化",
    "Base ": "基数",
    "Challenge (": "挑战 (",
    "In Base Challenge ": "在基数挑战中",
    "Keep ": "保留",
    "Multiply research upgrade effect by ": "将研究升级效果乘以",
    "Research ": "研究",
    "And extend the cap of Quantum ": "并扩展上限针对量子",
    "CPU upgrade effect ": "CPU升级效果",
    "Each bought Quantum Upgrade boosts Qubit gain by ": "每购买一次量子升级就增加量子位增益",
    "Each Grey digit boosts CPU by ": "每个灰色数位提高CPU",
    "Each Quantum Lab Boosts CPU by ": "每个量子实验室提高CPU",
    "Each Qubit boosts itself Production Speed by ": "每个量子位提高自身的生产速度",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\n": "",
    " of progress done!": "进度完成！",
    " left": "剩余",
    "Boost: Money": "提升: 金钱",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^([\d\.]+)   \$$/, //纯空格
//    /^(.+).exe$/,
    /^([\d\.]+)m$/, //纯空格
    /^([\d\.]+)e(\d+)   \$$/, //纯空格
    /^([\d\.]+)e(\d+) \$$/, //纯空格
    /^: ([\d\.]+)e(\d+) \/$/, //纯空格
    /^: (\d+) \/$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^You have (.+)\/(.+) Qubit \(next Qubit at Infinity sec\)$/, '你有 $1\/$2 量子位\(下一个量子位在 无限 秒\)'],
    [/^You need to reach (.+) to get next RP$/, '您需要达到 $1 才能获得下一个研究点'],
    [/^(\d+) extra process$/, '$1 额外进程'],
    [/^Can increase base with only (.+) digits$/, '可以增加基数只 $1 位数'],
    [/^Have (.+)\/(.+) Qubits$/, '有 $1\/$2 量子位'],
    [/^Go singularity (.+)\/(.+) times$/, '达到奇点 $1\/$2 次'],
    [/^Reach bulk (.+)\/(.+) Quantum Labs$/, '到达批量 $1\/$2 量子实验室'],
    [/^Complete (.+)\/(.+) Challenges$/, '完成 $1\/$2 挑战'],
    [/^If you Reboot now, you'll get (.+) Research Points$/, '如果你现在重启，你会得到 $1 研究点'],
    [/^\| (.+) RP\n\n   \| (.+) Qubit , \n   (.+) Lab\n \| (.+) SP$/, '\| $1 研究点\n\n   \| $2 量子位 , \n   $3 实验室\n \| $4 SP'],
    [/^You spent ([\d\.]+)d in this Singularity$/, '你在这个奇点待了 $1 天'],
    [/^You spent ([\d\.]+)h in this Singularity$/, '你在这个奇点待了 $1 小时'],
    [/^You spent ([\d\.]+)m in this Singularity$/, '你在这个奇点待了 $1 分钟'],
    [/^You spent ([\d\.]+)m in this Quantum$/, '你在这个量子待了 $1 分钟'],
    [/^You spent ([\d\.]+)d in this Quantum$/, '你在这个量子待了 $1 天'],
    [/^You spent ([\d\.]+)h in this Quantum$/, '你在这个量子待了 $1 小时'],
    [/^You spent ([\d\.]+)d in this Reboot$/, '你在这次重启待了 $1 天'],
    [/^You spent ([\d\.]+)h in this Reboot$/, '你在这次重启待了 $1 小时'],
    [/^You spent ([\d\.]+)m in this Reboot$/, '你在这次重启待了 $1 分钟'],
    [/^Each SP increases Multi Process by (.+) \(tot (.+), softcap at$/, '每个SP增加 $1 多进程 \(总计 $2，软上限在'],
    [/^You\'ve done Reboot (.+) times$/, '您已完成重启 $1 次'],
    [/^You\'ve gone Singularity (.+) times$/, '您已完成奇点 $1 次'],
    [/^You\'ve done Quantum (.+) times$/, '您已完成量子 $1 次'],
    [/^You have (.+)\/(.+) Qubit \(next Qubit in way too long$/, '您有 $1\/$2 量子位（下一量子位还要很久'],
    [/^Have (.+) SP to retain Keep (.+)$/, '拥有 $1 SP来保留 保留$2'],
    [/^Buy (.+)\/(.+) CPU upgrade$/, '购买 $1\/$2 CPU 升级'],
    [/^Have (.+)\/(.+) RP$/, '有 $1\/$2 研究点'],
    [/^You have (.+) Quantum Lab which makes Qubit Prodution (.+)x faster$/, '你有 $1 个量子实验室，这使得量子位的生产速度加快了 $2x'],
    [/^You have (.+)\/(.+) Qubit \(next Qubit in$/, '你有 $1\/$2 量子位 \(下一个量子位'],
    [/^(\d+) Qubit\n $/, '$1 量子位'],
    [/^Have (.+)\/(.+) \$$/, '有 $1\/$2 \$'],
    [/^Have (.+)\/(.+) Labs$/, '有 $1\/$2 实验室'],
    [/^Have (.+)\/(.+) Quantum Labs$/, '有 $1\/$2 量子实验室'],
    [/^Have (.+)\/(.+) Quantum Upgrades$/, '有 $1\/$2 量子升级'],
    [/^You have (.+) Research Points$/, '您有 $1 研究点'],
    [/^You have (.+) Singularity Power$/, '您有 $1 奇点功率'],
    [/^(\d+) Singularity Power$/, '$1 奇点功率'],
    [/^Each SP increases Multi Process by 4 \(tot (\d+), cap at 25\)$/, '每个SP将多进程增加4（总计$1，上限为25）'],
    [/^Go singularity (\d+)\/(\d+) times to enter Challenge \(Increases per challenge complete\)$/, '进行$1\/$2次奇点输入挑战（完成每个挑战增加）'],
[/^ċ(.+)...$/, 'ċ$1...'],
[/^ć(.+)...$/, 'ć$1...'],
[/^č(.+)...$/, 'č$1...'],
[/^Č(.+)...$/, 'Č$1...'],
[/^Ƈ(.+)...$/, 'Ƈ$1...'],
[/^ƌ(.+)...$/, 'ƌ$1...'],
[/^ď(.+)...$/, 'ď$1...'],
[/^ď(.+)...$/, 'ď$1...'],
[/^Đ(.+)...$/, 'Đ$1...'],
[/^Ď(.+)...$/, 'Ď$1...'],
[/^ē(.+)...$/, 'ē$1...'],
[/^ě(.+)...$/, 'ě$1...'],
[/^ę(.+)...$/, 'ę$1...'],
[/^ë(.+)...$/, 'ë$1...'],
[/^É(.+)...$/, 'É$1...'],
[/^Ĕ(.+)...$/, 'Ĕ$1...'],
[/^ğ(.+)...$/, 'ğ$1...'],
[/^ģ(.+)...$/, 'ģ$1...'],
[/^ĝ(.+)...$/, 'ĝ$1...'],
[/^ǥ(.+)...$/, 'ǥ$1...'],
[/^ǵ(.+)...$/, 'ǵ$1...'],
[/^Ģ(.+)...$/, 'Ģ$1...'],
[/^Ġ(.+)...$/, 'Ġ$1...'],
[/^Ğ(.+)...$/, 'Ğ$1...'],
[/^Ǥ(.+)...$/, 'Ǥ$1...'],
[/^ħ(.+)...$/, 'ħ$1...'],
[/^Ƕ(.+)...$/, 'Ƕ$1...'],
[/^ǰ(.+)...$/, 'ǰ$1...'],
[/^ǩ(.+)...$/, 'ǩ$1...'],
[/^Ǩ(.+)...$/, 'Ǩ$1...'],
[/^Ń(.+)...$/, 'Ń$1...'],
[/^Ñ(.+)...$/, 'Ñ$1...'],
[/^Ǹ(.+)...$/, 'Ǹ$1...'],
[/^ň(.+)...$/, 'ň$1...'],
[/^ǹ(.+)...$/, 'ǹ$1...'],
[/^õ(.+)...$/, 'õ$1...'],
[/^ö(.+)...$/, 'ö$1...'],
[/^ô(.+)...$/, 'ô$1...'],
[/^ó(.+)...$/, 'ó$1...'],
[/^ò(.+)...$/, 'ò$1...'],
[/^ǫ(.+)...$/, 'ǫ$1...'],
[/^Ǭ(.+)...$/, 'Ǭ$1...'],
[/^Ǫ(.+)...$/, 'Ǫ$1...'],
[/^ş(.+)...$/, 'ş$1...'],
[/^Ś(.+)...$/, 'Ś$1...'],
[/^Ş(.+)...$/, 'Ş$1...'],
[/^š(.+)...$/, 'š$1...'],
[/^ŗ(.+)...$/, 'ŗ$1...'],
[/^ř(.+)...$/, 'ř$1...'],
[/^ŕ(.+)...$/, 'ŕ$1...'],
[/^Ŗ(.+)...$/, 'Ŗ$1...'],
[/^Ř(.+)...$/, 'Ř$1...'],
[/^Ŕ(.+)...$/, 'Ŕ$1...'],
[/^Ŝ(.+)...$/, 'Ŝ$1...'],
[/^Š(.+)...$/, 'Š$1...'],
[/^ŝ(.+)...$/, 'ŝ$1...'],
[/^ś(.+)...$/, 'ś$1...'],
[/^ť(.+)...$/, 'ť$1...'],
[/^ú(.+)...$/, 'ú$1...'],
[/^ű(.+)...$/, 'ű$1...'],
[/^ū(.+)...$/, 'ū$1...'],
[/^ũ(.+)...$/, 'ũ$1...'],
[/^Ű(.+)...$/, 'Ű$1...'],
[/^Ů(.+)...$/, 'Ů$1...'],
[/^ų(.+)...$/, 'ų$1...'],
[/^Ũ(.+)...$/, 'Ũ$1...'],
[/^Ų(.+)...$/, 'Ų$1...'],
[/^Ÿ(.+)...$/, 'Ÿ$1...'],
[/^Ŷ(.+)...$/, 'Ŷ$1...'],
[/^ŷ(.+)...$/, 'ŷ$1...'],
[/^Ž(.+)...$/, 'Ž$1...'],
[/^Ź(.+)...$/, 'Ź$1...'],
[/^Ż(.+)...$/, 'Ź$1...'],
[/^ź(.+)...$/, 'ź$1...'],
[/^ż(.+)...$/, 'ż$1...'],
[/^ž(.+)...$/, 'ž$1...'],
[/^ø(.+)...$/, 'ø$1...'],
[/^Ə(.+)...$/, 'ø$1...'],
[/^Ɛ(.+)...$/, 'Ɛ$1...'],
[/^Ƹ(.+)...$/, 'Ɛ$1...'],
[/^ƺ(.+)...$/, 'Ɛ$1...'],
[/^ǘ(.+)...$/, 'Ɛ$1...'],
[/^Ǚ(.+)...$/, 'Ɛ$1...'],
[/^ǚ(.+)...$/, 'Ɛ$1...'],
[/^ƻ(.+)...$/, 'Ɛ$1...'],
[/^ƿ(.+)...$/, 'Ɛ$1...'],
[/^Ʒ(.+)...$/, 'ǅ$1...'],
[/^ǅ(.+)...$/, 'ǅ$1...'],
[/^Ǳ(.+)...$/, 'ǅ$1...'],
[/^ȃ(.+)...$/, 'ǅ$1...'],
[/^Ȃ(.+)...$/, 'ǅ$1...'],
[/^Ȅ(.+)...$/, 'ǅ$1...'],
[/^ȇ(.+)...$/, 'ǅ$1...'],
[/^ȅ(.+)...$/, 'ǅ$1...'],
[/^Ȇ(.+)...$/, 'ǅ$1...'],
[/^Ȉ(.+)...$/, 'ǅ$1...'],
[/^ƴ(.+)...$/, 'ǅ$1...'],
[/^Ɣ(.+)...$/, 'ǅ$1...'],
[/^ƕ(.+)...$/, 'ǅ$1...'],
[/^Ł(.+)...$/, 'ǅ$1...'],
[/^ļ(.+)...$/, 'ǅ$1...'],
[/^ǉ(.+)...$/, 'ǅ$1...'],
[/^Ǉ(.+)...$/, 'ǅ$1...'],
[/^ņ(.+)...$/, 'ǅ$1...'],
[/^ń(.+)...$/, 'ǅ$1...'],
[/^ǌ(.+)...$/, 'ǅ$1...'],
[/^ǋ(.+)...$/, 'ǅ$1...'],
[/^ƒ(.+)...$/, 'ǅ$1...'],
[/^Ƒ(.+)...$/, 'ǅ$1...'],
[/^Ɠ(.+)...$/, 'ǅ$1...'],
[/^Ħ(.+)...$/, 'ǅ$1...'],
[/^ĥ(.+)...$/, 'ǅ$1...'],
[/^Ǐ(.+)...$/, 'ǅ$1...'],
[/^į(.+)...$/, 'ǅ$1...'],
[/^ȉ(.+)...$/, 'ǅ$1...'],
[/^ǐ(.+)...$/, 'ǅ$1...'],
[/^ì(.+)...$/, 'ǅ$1...'],
[/^Ĳ(.+)...$/, 'ǅ$1...'],
[/^ī(.+)...$/, 'ǅ$1...'],
[/^ơ(.+)...$/, 'ǅ$1...'],
[/^ƞ(.+)...$/, 'ǅ$1...'],
[/^ǒ(.+)...$/, 'ǅ$1...'],
[/^ĸ(.+)...$/, 'ǅ$1...'],
[/^ǿ(.+)...$/, 'ǅ$1...'],
[/^Ŋ(.+)...$/, 'ǅ$1...'],
[/^Ò(.+)...$/, 'ǅ$1...'],
[/^Ĵ(.+)...$/, 'ǅ$1...'],
[/^Ķ(.+)...$/, 'ǅ$1...'],
[/^ķ(.+)...$/, 'ǅ$1...'],
[/^ļ(.+)...$/, 'ǅ$1...'],
[/^ĺ(.+)...$/, 'ǅ$1...'],
[/^İ(.+)...$/, 'ǅ$1...'],
[/^Ƶ(.+)...$/, 'ǅ$1...'],
//下面的发布时不要
//[/^1(.+)...$/, '1$1...'],
//[/^2(.+)...$/, '2$1...'],
//[/^3(.+)...$/, '3$1...'],
//[/^4(.+)...$/, '4$1...'],
//[/^5(.+)...$/, '5$1...'],
//[/^6(.+)...$/, '6$1...'],
//[/^7(.+)...$/, '7$1...'],
//[/^8(.+)...$/, '8$1...'],
//[/^9(.+)...$/, '9$1...'],
//[/^0(.+)...$/, '0$1...'],
//[/^A(.+)...$/, 'A$1...'],
//[/^B(.+)...$/, 'B$1...'],
//[/^C(.+)...$/, 'C$1...'],
//[/^D(.+)...$/, 'D$1...'],
//[/^E(.+)...$/, 'E$1...'],
//[/^F(.+)...$/, 'F$1...'],
//[/^G(.+)...$/, 'G$1...'],
//[/^H(.+)...$/, 'H$1...'],
//[/^I(.+)...$/, 'I$1...'],
//[/^J(.+)...$/, 'J$1...'],
//[/^K(.+)...$/, 'K$1...'],
//[/^L(.+)...$/, 'L$1...'],
//[/^M(.+)...$/, 'M$1...'],
//[/^N(.+)...$/, 'N$1...'],
//[/^O(.+)...$/, 'O$1...'],
//[/^P(.+)...$/, 'P$1...'],
//[/^Q(.+)...$/, 'Q$1...'],
//[/^R(.+)...$/, 'R$1...'],
//[/^S(.+)...$/, 'S$1...'],
//[/^T(.+)...$/, 'T$1...'],
//[/^U(.+)...$/, 'U$1...'],
//[/^V(.+)...$/, 'V$1...'],
//[/^W(.+)...$/, 'W$1...'],
//[/^X(.+)...$/, 'X$1...'],
//[/^Y(.+)...$/, 'Y$1...'],
//[/^Z(.+)...$/, 'Z$1...'],
//[/^a(.+)...$/, 'a$1...'],
//[/^b(.+)...$/, 'b$1...'],
//[/^c(.+)...$/, 'c$1...'],
//[/^d(.+)...$/, 'd$1...'],
//[/^e(.+)...$/, 'e$1...'],
//[/^f(.+)...$/, 'f$1...'],
//[/^g(.+)...$/, 'g$1...'],
//[/^h(.+)...$/, 'h$1...'],
//[/^i(.+)...$/, 'i$1...'],
//[/^j(.+)...$/, 'j$1...'],
//[/^k(.+)...$/, 'k$1...'],
//[/^m(.+)...$/, 'm$1...'],
//[/^n(.+)...$/, 'n$1...'],
//[/^o(.+)...$/, 'o$1...'],
//[/^p(.+)...$/, 'p$1...'],
//[/^q(.+)...$/, 'q$1...'],
//[/^r(.+)...$/, 'r$1...'],
//[/^s(.+)...$/, 's$1...'],
//[/^t(.+)...$/, 't$1...'],
//[/^u(.+)...$/, 'u$1...'],
//[/^v(.+)...$/, 'v$1...'],
//[/^w(.+)...$/, 'w$1...'],
//[/^x(.+)...$/, 'x$1...'],
//[/^y(.+)...$/, 'y$1...'],
//[/^z(.+)...$/, 'z$1...'],
]);
