/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    '& Quantum Reset': '& 量子重置',
    'Option': '选项',
    'Quantity': '数量',
    'Quantum': '量子',
    'Qubit': '量子位',
    'Research': '研究',
    'Restart': '重新开始',
    'name': '名称',
    'New Age': '新世纪',
    'None': '无',
    'Output': '输出',
    'Money': '货币',
    'Achievement': '成就',
    'Challenge': '挑战',
    'Cost': '成本',
    'Export': '导出',
    'Extra Digit': '额外数位',
    'Hard Reset': '硬复位',
    'Hotkeys': '快捷键',
    'hehe': '呵呵',
    'Import': '导入',
    'Incrementer': '增量器',
    'Infinity Boost': '无限提升',
    'Lab Town': '实验室镇',
    'Make': '制作',
    'Module': '模块',
    'More Challenges': '更多挑战',
    'Multi Process': '多进程',
    'My Discord': '我的Discord',
    'Reboot': '重启',
    'Reboot Cool Down': '重新启动冷却',
    'Programs': '程序',
    'load': '加载',
    'Make speed': '制作速度',
    'Larger Memory': '更大的内存',
    'Infinity Research': '无限研究',
    'Lab': '实验室',
    'Durability': '耐用性',
    'Run': '运行',
    'Sacrifice': '牺牲',
    'Save': '保存',
    'Shop': '商店',
    'Singularit': '奇点',
    'Singularity': '奇点',
    'Speed': '速度',
    'Stat': '统计',
    'Ultimate Science': '终极科学',
    'Upgrades': '升级',
    'Upgrade!': '升级!',
    'Base': '基础',
    'Boost!': '提升!',
    'Booster': '加速器',
    'Bugged Reality': '错误的现实',
    'Broken Machine': '破碎机',
    'Bulk QL Challenge': '散装QL挑战',
    'CPU upgrade level +': 'CPU升级等级 +',
    'decrease speed /': '降低速度 /',
    'Digit': '数位',
    'Boost': '提升',
    'Effects': '效果',
    'Exit challenge': '退出挑战',
    'Game speed': '游戏速度',
    'Tech lab?': '技术实验室？',
    'Second Singularity': '第二奇点',
    'Skilled': '熟练',
    'Rich': '富有',
    'Richer': '更富有',
    'Respec': '规格',
    'Base +': '基础 +',
    'Bonus CPU Level': '额外的CPU等级',
    'Multiply mine power by Digits': '数位乘以矿山的力量',
    'RP Gain': '研究点收益',
    'RP gain': '研究点收益',
    'Sacrifice II': '牺牲 II',
    'Savefiles': '保存文件',
    'Theme: Default': '主题: 默认',
    'Theme: None': '主题: 无',
    'Tricky': '棘手',
    'Undo': '撤销',
    'x faster': 'x 更快',
    'Grid': '网格',
    'Grid Lab': '网格实验室',
    'Infinity': '无限',
    'Info': '信息',
    'Merger': '合并',
    'Mastered': '精通',
    'Max digit +': '最大数位 +',
    'Lv.': '等级',
    'Max Durability': '最大耐久度',
    'Max program run at one time +': '一次最多可运行程序+',
    'Memory exceed': '内存超过',
    'Mult': '乘以',
    'R.Speed': 'R.速度',
    'la la la': '啦啦啦',
    'Inf..': '无限..',
    'R: reboot': 'R: 重启',
    'Q: build lab': 'Q: 建造实验室',
    '8: Toggle all programs': '8：切换所有程序',
    '1 ~ 7: Toggle program 1~': '1〜7：切换程序1〜',
    'Go singularity one more time': '再来一次奇点',
    'Go Singularity in 1e+110/500 milliseconds': '在1e+110/500毫秒内到达奇点',
    'Go singularity': '到达奇点',
    'Complete a challenge': '完成一个挑战',
    'Complete Boost Challenge': '完成提升挑战',
    'Complete Boost Challenge once': '完成提升挑战一次',
    'Complete Qubit Challenge once': '完成量子位挑战一次',
    'Can bulk complete Challenge': '可以批量完成挑战',
    'Buy all Quantum Upgrades': '购买所有量子升级',
    'All Challenge requirement -': '所有挑战要求-',
    'Increase digit won\'t reset anything': '增加数位不会重置任何东西',
    'Keep your Base and Programs on reboot': '在重启时保留你的基础和程序',
    'More Quantum Upgrades': '更多量子升级',
    'Multiply Mine power by': '挖矿功率乘以',
    'Multiply mine power by': '挖矿功率乘以',
    'Multiply RP gain based on itself': '根据自身乘以研究点增益',
    'nvaild savefile!': '无效的存档文件！',
    'Research speed': '研究速度',
    'Research Speed': '研究速度',
    'Reward': '奖励',
    'save': '保存',
    'savefile!': '存档文件！',
    'Shift Qubit production by +': '将量子位产生量改为 +',
    'Start challenge with half of goal QL (max.': '开始挑战的一半目标QL(最大。',
    'Start Quantum run with 100 RP': '启动量子运行100研究点',
    'Theme: Aqua': '主题：水色',
    'Theme: Compact': '主题：紧凑',
    'Theme: Magenta (by RedMountain': '主题：洋红色（作者：RedMountain',
    'to clipboard': '到剪贴板',
    'way too long left': '还剩太久',
    '^0.9 Quantum requirements': '^ 0.9量子需求',
    'CPU speed': 'CPU速度',
    'Go Infinity in 10 seconds': '在10秒内达到无限',
    "Qubit production speed": "量子位的生产速度",
    "Reach 111111(": "达到 111111(",
    'SP gain': 'SP 收益',
    'upgrade CPU': '升级CPU',
    'Achievement: A Dollar': '成就：一美元',
    'time / x IP': '时间 / x 无限点',
    'Infinity QL': '无限 QL',
    'Multiply mine power by Research Point': '通过研究点乘以矿山的能量',
    'You lose': '你会损失',
    'You lose Money, Upgrades': '你会损失金钱和升级',
    'You lose Money, Upgrades, Digit, Number': '你会损失金钱和升级，数位，数字',
    'You lose Money, Upgrades, Digit, Number, Base': '你会损失金钱和升级，数位，数字, 基于',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'Boost Qubit gain speed based on Challenge Completions (^': '提高量子位加速基于挑战完成(^',
    'A, S, D, F, G, H, J: Open tabs': 'A, S, D, F, G, H, J: 打开标签',
    '2 more?': '再来2个?',
    '2 Merger Grid Machine': '2合并网格机',
    '2 Grid Space': '2网格空间',
    'You need to reach 11110100001000111111111111(2) to get next RP': '需要到达11110100001000111111111111(2)才能得到下一个研究点',
    'You lose Money, Upgrades, Digit, Number, Base on Reboot': '您会因重启而损失金钱，升级，数位，数字',
    'export game to clipboard': '导出存档到剪贴板',
    'file!': '文件!',
    'game to clipboard': '存档到剪贴板',
    'Generate 10% of SP gain per second': '每秒产生10%的SP增益',
    'Go Infinity in 5 hours': '在5个小时内达到无限',
    'Keep your base(cap: 36), programs on reboot': '保持你的基础（上限：36），重新启动程序',
    'Need 80 Quantum Labs to go Singularity': '需要80个量子实验室才能实现奇点',
    'Power of Science': '科学的力量',
    'one machine of its type, as well as one extra Incrementer machine, SP and Qubit': '一台同类型的机器，以及一台额外的增量机，SP和量子位',
    'Offline Progress': '离线进度',
    'Notation: Logarithm': '符号:对数',
    'Notation: Default': '符号:默认',
    'Make it better, but durability will decrease faster': '让它变得更好，但是耐用性会下降得更快',
    'If you Reboot now, you\'ll get 0 Research Points': '如果你现在重启，你将得到0个研究点',
    'Give me more QUBIT!': '给我更多的量子位！',
    'Each Qubit makes your CPU 2x faster': '每一个量子位都使你的CPU速度提高两倍',
    'Digit +': '数位 +',
    'Ctrl: See advanced information': 'Ctrl:查看高级信息',
    'Complete 4 more challenges to unlock 5th Grid space': '完成更多4个挑战，解锁第五个格子空间',
    'Clicking the above upgrade will use 10% of your IP': '点击以上升级将使用10%的IP',
    'Challenge completion reward is': '挑战完成奖励是',
    'Buy upgrade for': '购买升级',
    'Shift + H: Toggle Hyper mode! - More fancy effects, more lag!': 'Shift + H:切换超模式!-更多的特效，更多的延迟!',
    'Shift + P: Pause the game': 'Shift + P:暂停游戏',
    'Singularity at light speed': '光速奇点',
    'You have 0/0 Qubit (next Qubit at Infinity sec': '你有0/0量子位(下一个量子位在无穷秒',
    'You have 0 Quantum Lab which makes Qubit Prodution 0x faster': '你有0量子实验室，使量子位的生产速度快0x',
    'You lose Number, Memery, Base, Monsy, Upgrades on Reboot': '您在重新启动时丢失了数字，内存，基础，金钱，升级',
    'You have 0 Infinity Points': '你有 0 无限点',
    'Reward of challenges are one of it\'s Machine, a Incrementer, a SP and a Extra Qubit': '挑战的奖励是它的一个机器，一个增量器，一个SP和一个额外的量子位元',
    'Shift + 1 ~ 8: Buy research 1 ~': 'Shift + 1〜8：购买研究1〜',
    'Upgrade durability to use overclock longer': '升级耐用性以延长超频时间',
    'Buy CPU upgrade automatically': '购买CPU自动升级',
    'You\'ve played this game for': '你玩了这个游戏',
    'You need to reach 63,999,999(10) to Reboot': '您需要达到63,999,999（10）才能重启',
    'Increase your base to store more number': '增加你的基础存储更多的数字',
    'Let\'s count to ten': '数到十',
    'Overclocker effect x2, but Durability decrease speed +': '超频效果x2，但耐用性降低速度 +',
    'Multiply mine power by digits': '通过数位乘以矿用电力',
    'A Dollar': '一美元',

    //原样
    'test desc': '测试描述',
    'RP': '研究点',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "Quantum ": "量子",
    'Number': '数字',
    "Overclock ": "超频",
    'Durability ': '耐用性',
    "Speed Challenge ": "速度挑战",
    "Start durability": "开始耐久性",
    "Challene Fail:": "挑战失败:",
    "Booster Challenge": "助推器挑战",
    "Next Lab:": "下个实验室:",
    "Reboot Cooldown": "重启冷却",
    "RP Challenge (": "研究点挑战 (",
    "A to ": "A 到 ",
    "Digit Challenge (": "数位挑战 (",
    "Base Challenge (": "基础挑战 (",
    "Money Challenge (": "金钱挑战 (",
    "Goal: ": "目标: ",
    "Process ": "进程 ",
    "Digit: ": "数位: ",
    "Base: ": "基础: ",
    "Qubit Challenge (": "量子位挑战 (",
    "R.Speed Challenge (": "重启速度调整 (",
    "Reboot cooldown ": "重启冷却时间 ",
    "Reach base ": "达到基础 ",
    "Reach Bonus CPU Level ": "达到奖励CPU等级 ",
    "Reach Extra Digit Level ": "达到额外数位等级 ",
    "Reach Infinity$ (cap of ": "达到无限$ (上限是 ",
    "Reach Multi Process Level ": "达到多进程等级 ",
    "Shop cost": "商店成本",
    "Perform Overclock with Power ": "用能量进行超频 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\n": "",
    " of progress done!": "进度完成！",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^([\d\.]+)   \$$/, //纯空格
    /^([\d\.]+)e(\d+)   \$$/, //纯空格
    /^: ([\d\.]+)e(\d+) \/$/, //纯空格
    /^: (\d+) \/$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^You have (.+)\/(.+) Qubit \(next Qubit at Infinity sec\)$/, '你有 $1\/$2 量子位\(下一个量子位在 无限 秒\)'],
    [/^You need to reach (.+) to get next RP$/, '您需要达到 $1 才能获得下一个研究点'],
    [/^(\d+) extra process$/, '$1 额外进程'],
    [/^Can increase base with only (.+) digits$/, '可以增加基础只 $1 位数'],
    [/^Have (.+)\/(.+) Qubits$/, '有 $1\/$2 量子位'],
    [/^Go singularity (.+)\/(.+) times$/, '达到奇点 $1\/$2 次'],
    [/^Reach bulk (.+)\/(.+) Quantum Labs$/, '到达批量 $1\/$2 量子实验室'],
    [/^Complete (.+)\/(.+) Challenges$/, '完成 $1\/$2 挑战'],
    [/^Have (.+)\/(.+) RP$/, '有 $1\/$2 研究点'],
    [/^Have (.+)\/(.+) \$$/, '有 $1\/$2 \$'],
    [/^Have (.+)\/(.+) Labs$/, '有 $1\/$2 实验室'],
    [/^Have (.+)\/(.+) Quantum Labs$/, '有 $1\/$2 量子实验室'],
    [/^Have (.+)\/(.+) Quantum Upgrades$/, '有 $1\/$2 量子升级'],
    [/^You have (.+) Research Points$/, '您有 $1 研究点'],
    [/^You have (.+) Singularity Power$/, '您有 $1 奇点功率'],
    [/^Each SP increases Multi Process by 4 \(tot (\d+), cap at 25\)$/, '每个SP将多进程增加4（总计$1，上限为25）'],
    [/^Go singularity (\d+)\/(\d+) times to enter Challenge \(Increases per challenge complete\)$/, '进行$1\/$2次奇点输入挑战（完成每个挑战增加）'],
]);