/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    '& Quantum Reset': '& 量子重置',
    'Option': '选项',
    'Quantity': '数量',
    'Quantum': '量子',
    'Qubit': '量子位',
    'Research': '研究',
    'Restart': '重新开始',
    'name': '名称',
    'New Age': '新世纪',
    'None': '无',
    'Output': '输出',
    'Money': '货币',
    'Achievement': '成就',
    'Challenge': '挑战',
    'Cost': '成本',
    'Export': '导出',
    'Extra Digit': '额外数字',
    'Hard Reset': '硬复位',
    'Hotkeys': '快捷键',
    'hehe': '呵呵',
    'Import': '导入',
    'Incrementer': '增量器',
    'Infinity Boost': '无限提升',
    'Lab Town': '实验室镇',
    'Make': '制作',
    'Module': '模块',
    'More Challenges': '更多挑战',
    'Multi Process': '多进程',
    'My Discord': '我的Discord',
    'Reboot': '重启',
    'Reboot Cool Down': '重新启动冷却',
    'Programs': '程序',
    'load': '加载',
    'Make speed': '制作速度',
    'Larger Memory': '更大的内存',
    'Infinity Research': '无限研究',
    'Lab': '实验室',
    'Durability': '耐用性',
    'Run': '运行',
    'Sacrifice': '牺牲',
    'Save': '保存',
    'Shop': '商店',
    'Singularit': '奇点',
    'Singularity': '奇点',
    'Speed': '速度',
    'Stat': '统计',
    'Ultimate Science': '终极科学',
    'Upgrades': '升级',
    'Upgrade!': '升级!',
    'Base': '基础',
    'Boost!': '提升!',
    'Booster': '加速器',
    'Bugged Reality': '错误的现实',
    'Broken Machine': '破碎机',
    'Bulk QL Challenge': '散装QL挑战',
    'CPU upgrade level +': 'CPU升级等级 +',
    'decrease speed /': '降低速度 /',
    'Digit': '数字',
    'Boost': '提升',
    'Effects': '效果',
    'Exit challenge': '退出挑战',
    'Game speed': '游戏速度',
    'Tech lab?': '技术实验室？',
    'Second Singularity': '第二奇点',
    'Skilled': '熟练',
    'Rich': '富有',
    'Richer': '更富有',
    'Respec': '规格',
    'Base +': '基础 +',
    'Bonus CPU Level': '额外的CPU等级',
    'Multiply mine power by Digits': '数字乘以矿山的力量',
    'RP Gain': 'RP收益',
    'RP gain': 'RP收益',
    'Sacrifice II': '牺牲 II',
    'Savefiles': '保存文件',
    'Theme: Default': '主题: 默认',
    'Theme: None': '主题: 无',
    'Tricky': '棘手',
    'Undo': '撤销',
    'x faster': 'x 更快',
    'Grid': '网格',
    'Grid Lab': '网格实验室',
    'Infinity': '无限',
    'Info': '信息',
    'Merger': '合并',
    'Mastered': '精通',
    'Max digit +': '最大数字 +',
    'Lv.': '等级',
    'Max Durability': '最大耐久度',
    'Max program run at one time +': '一次最多可运行程序+',
    'Memory exceed': '内存超过',
    'Mult': '乘以',
    'R.Speed': 'R.速度',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'Need 80 Quantum Labs to go Singularity': '需要80个量子实验室才能实现奇点',
    'Power of Science': '科学的力量',
    'one machine of its type, as well as one extra Incrementer machine, SP and Qubit': '一台同类型的机器，以及一台额外的增量机，SP和量子位',
    'Offline Progress': '离线进度',
    'Notation: Logarithm': '符号:对数',
    'Notation: Default': '符号:默认',
    'Make it better, but durability will decrease faster': '让它变得更好，但是耐用性会下降得更快',
    'If you Reboot now, you\'ll get 0 Research Points': '如果你现在重启，你将得到0个研究点',
    'Give me more QUBIT!': '给我更多的量子位！',
    'Each Qubit makes your CPU 2x faster': '每一个量子位都使你的CPU速度提高两倍',
    'Digit +': '数字 +',
    'Ctrl: See advanced information': 'Ctrl:查看高级信息',
    'Complete 4 more challenges to unlock 5th Grid space': '完成更多4个挑战，解锁第五个格子空间',
    'Clicking the above upgrade will use 10% of your IP': '点击以上升级将使用10%的IP',
    'Challenge completion reward is': '挑战完成奖励是',
    'Buy upgrade for': '购买升级',
    'Shift + H: Toggle Hyper mode! - More fancy effects, more lag!': 'Shift + H:切换超模式!-更多的特效，更多的延迟!',
    'Shift + P: Pause the game': 'Shift + P:暂停游戏',
    'Singularity at light speed': '光速奇点',
    'You have 0/0 Qubit (next Qubit at Infinity sec': '你有0/0量子位(下一个量子位在无穷秒',
    'You have 0 Quantum Lab which makes Qubit Prodution 0x faster': '你有0量子实验室，使量子比特的生产速度快0x',
    'You lose Number, Memery, Base, Monsy, Upgrades on Reboot': '您在重新启动时丢失了数字，内存，基础，金钱，升级',
    'You have 0 Infinity Points': '你有 0 无限点',
    'Reward of challenges are one of it\'s Machine, a Incrementer, a SP and a Extra Qubit': '挑战的奖励是它的一个机器，一个增量器，一个SP和一个额外的量子位元',
    'Shift + 1 ~ 8: Buy research 1 ~': 'Shift + 1〜8：购买研究1〜',
    'Upgrade durability to use overclock longer': '升级耐用性以延长超频时间',
    'Buy CPU upgrade automatically': '购买CPU自动升级',
    'You\'ve played this game for': '你玩了这个游戏',
    'You need to reach 63,999,999(10) to Reboot': '您需要达到63,999,999（10）才能重启',
    'Increase your base to store more number': '增加你的基础存储更多的数字',
    'Let\'s count to ten': '数到十',
    'Overclocker effect x2, but Durability decrease speed +': '超频效果x2，但耐用性降低速度 +',
    'Multiply mine power by digits': '通过数字乘以矿用电力',
    'A Dollar': '一美元',

    //原样
    'test desc': '测试描述',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "Quantum ": "量子",
    'Number': '数字',
    "Overclock ": "超频",
    'Durability ': '耐用性',
    "Speed Challenge ": "速度挑战",
    "Start durability": "开始耐久性",
    "Challene Fail:": "挑战失败:",
    "Booster Challenge": "助推器挑战",
    "Next Lab:": "下个实验室:",
    "Reboot Cooldown": "重启冷却",
    "RP Challenge (": "RP 挑战 (",
    "A to ": "A 到 ",
    "Digit Challenge (": "数字挑战 (",
    "Base Challenge (": "基础挑战 (",
    "Money Challenge (": "金钱挑战 (",
    "Goal: ": "目标: ",
    "Process ": "进度 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\n": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^You have (.+) Research Points$/, '您有 $1 研究点'],
    [/^You have (.+) Singularity Power$/, '您有 $1 奇点功率'],
]);